development:
  consumer_key: CHANGE_ME
  consumer_secret: CHANGE_ME
  access_token: CHANGE_ME
  access_token_secret: CHANGE_ME

production:
  consumer_key: CHANGE_ME
  consumer_secret: CHANGE_ME
  access_token: CHANGE_ME
  access_token_secret: CHANGE_ME