development:
  consumer_key: anmMaSX0JxdpsPVgVh4ILUL2Q
  consumer_secret: YqCUzKYMfAPALs9LvnbkqyZD8uz7vSMfujpJbX8RiN6Yth8wJv
  access_token: 99428558-DeQx0ViftBnzWDBfcxcO84RwpkRVytjVGHY4CZJQZ
  access_token_secret: LYgSOdXONheOaGXkDezSPHeg5GKYcyMv3YlDfZiTT49i7

production:
  api_key: CHANGE_ME
  api_secret: CHANGE_ME
  access_token: CHANGE_ME
  access_token_secret: CHANGE_ME